import { Preset } from './types';

export const STYLE_PRESETS: Preset[] = [
  {
    id: 'jarre-oxygene',
    label: 'Jarre Oxygène',
    description: 'Jean-Michel Jarre-style ambient space: analog bass, slow arps, vast pads, soft drums. 108 BPM, D minor, 32 bars.',
    imageUrl: 'https://images.unsplash.com/photo-1534258936925-c48947387e3b?auto=format&fit=crop&w=800&q=80',
    bpm: 108,
    bars: 32,
    key: 'D',
    scale: 'minor',
    style: 'jarre',
  },
  {
    id: 'kavinsky-drive',
    label: 'Kavinsky Drive',
    description: 'Synthwave in the style of Kavinsky: punchy side-chained drums, detuned bass, anthem lead, neon pads. 110 BPM, A minor, 24 bars.',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    bpm: 110,
    bars: 24,
    key: 'A',
    scale: 'minor',
    style: 'synthwave',
  },
  {
    id: 'guetta-dance',
    label: 'Guetta Dance',
    description: 'Energetic EDM/big-room in the style of David Guetta: four-on-floor kick, clap, big chords, festival lead. 128 BPM, D minor, 16 bars.',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    bpm: 128,
    bars: 16,
    key: 'D',
    scale: 'minor',
    style: 'dance',
  },
  {
    id: 'ambient-space',
    label: 'Ambient Space',
    description: 'Calm cosmic ambient: slow pads, gentle arps, minimal drums, lots of reverb. 90 BPM, C major, 32 bars.',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
    bpm: 90,
    bars: 32,
    key: 'C',
    scale: 'major',
    style: 'ambient',
  },
  {
    id: 'techno-club',
    label: 'Techno Club',
    description: 'Driving techno: tight kick, crisp hats, acid bass, stabs, evolving arrangement. 130 BPM, F minor, 16 bars.',
    imageUrl: 'https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?auto=format&fit=crop&w=800&q=80',
    bpm: 130,
    bars: 16,
    key: 'F',
    scale: 'minor',
    style: 'techno',
  },
];

export const DEFAULT_PRESET = STYLE_PRESETS[0];
